//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olfactory.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Test_OP_FreshAir {
            get {
                return ((double)(this["Test_OP_FreshAir"]));
            }
            set {
                this["Test_OP_FreshAir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>4</string>\r\n  <string>8</string>\r\n  <string>16</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Test_OP_OdorQuantities {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Test_OP_OdorQuantities"]));
            }
            set {
                this["Test_OP_OdorQuantities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Test_OP_InitialPause {
            get {
                return ((int)(this["Test_OP_InitialPause"]));
            }
            set {
                this["Test_OP_InitialPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Test_OP_OdorFlowDuration {
            get {
                return ((int)(this["Test_OP_OdorFlowDuration"]));
            }
            set {
                this["Test_OP_OdorFlowDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Test_OP_FinalPause {
            get {
                return ((int)(this["Test_OP_FinalPause"]));
            }
            set {
                this["Test_OP_FinalPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Test_OP_PIDReadingInterval {
            get {
                return ((int)(this["Test_OP_PIDReadingInterval"]));
            }
            set {
                this["Test_OP_PIDReadingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Test_OP_Valve2User {
            get {
                return ((bool)(this["Test_OP_Valve2User"]));
            }
            set {
                this["Test_OP_Valve2User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Logger_Folder {
            get {
                return ((string)(this["Logger_Folder"]));
            }
            set {
                this["Logger_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Setup_MFC_FreshAir {
            get {
                return ((double)(this["Setup_MFC_FreshAir"]));
            }
            set {
                this["Setup_MFC_FreshAir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double Setup_MFC_Odor {
            get {
                return ((double)(this["Setup_MFC_Odor"]));
            }
            set {
                this["Setup_MFC_Odor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Setup_MFC_Valve1 {
            get {
                return ((int)(this["Setup_MFC_Valve1"]));
            }
            set {
                this["Setup_MFC_Valve1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setup_MFC_Valve2 {
            get {
                return ((int)(this["Setup_MFC_Valve2"]));
            }
            set {
                this["Setup_MFC_Valve2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setup_MFCPort {
            get {
                return ((string)(this["Setup_MFCPort"]));
            }
            set {
                this["Setup_MFCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setup_PIDPort {
            get {
                return ((string)(this["Setup_PIDPort"]));
            }
            set {
                this["Setup_PIDPort"] = value;
            }
        }
    }
}
