//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olfactory.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Test_OP_FreshAir {
            get {
                return ((double)(this["Test_OP_FreshAir"]));
            }
            set {
                this["Test_OP_FreshAir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 8x500, 16x500x2, 32x2")]
        public string Test_OP_OdorQuantityList {
            get {
                return ((string)(this["Test_OP_OdorQuantityList"]));
            }
            set {
                this["Test_OP_OdorQuantityList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Test_OP_InitialPause {
            get {
                return ((int)(this["Test_OP_InitialPause"]));
            }
            set {
                this["Test_OP_InitialPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double Test_OP_OdorFlowDuration {
            get {
                return ((double)(this["Test_OP_OdorFlowDuration"]));
            }
            set {
                this["Test_OP_OdorFlowDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Test_OP_FinalPause {
            get {
                return ((int)(this["Test_OP_FinalPause"]));
            }
            set {
                this["Test_OP_FinalPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Test_OP_PIDReadingInterval {
            get {
                return ((int)(this["Test_OP_PIDReadingInterval"]));
            }
            set {
                this["Test_OP_PIDReadingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int Test_OP_ValvesControlled {
            get {
                return ((int)(this["Test_OP_ValvesControlled"]));
            }
            set {
                this["Test_OP_ValvesControlled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Logger_Folder {
            get {
                return ((string)(this["Logger_Folder"]));
            }
            set {
                this["Logger_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Setup_MFC_FreshAir {
            get {
                return ((double)(this["Setup_MFC_FreshAir"]));
            }
            set {
                this["Setup_MFC_FreshAir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double Setup_MFC_Odor {
            get {
                return ((double)(this["Setup_MFC_Odor"]));
            }
            set {
                this["Setup_MFC_Odor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Setup_MFC_Valve1 {
            get {
                return ((int)(this["Setup_MFC_Valve1"]));
            }
            set {
                this["Setup_MFC_Valve1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setup_MFC_Valve2 {
            get {
                return ((int)(this["Setup_MFC_Valve2"]));
            }
            set {
                this["Setup_MFC_Valve2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setup_MFCPort {
            get {
                return ((string)(this["Setup_MFCPort"]));
            }
            set {
                this["Setup_MFCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setup_PIDPort {
            get {
                return ((string)(this["Setup_PIDPort"]));
            }
            set {
                this["Setup_PIDPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double App_ZoomLevel {
            get {
                return ((double)(this["App_ZoomLevel"]));
            }
            set {
                this["App_ZoomLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_Width {
            get {
                return ((double)(this["MainWindow_Width"]));
            }
            set {
                this["MainWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_Height {
            get {
                return ((double)(this["MainWindow_Height"]));
            }
            set {
                this["MainWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_X {
            get {
                return ((double)(this["MainWindow_X"]));
            }
            set {
                this["MainWindow_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_Y {
            get {
                return ((double)(this["MainWindow_Y"]));
            }
            set {
                this["MainWindow_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MonitorWindow_Width {
            get {
                return ((double)(this["MonitorWindow_Width"]));
            }
            set {
                this["MonitorWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MonitorWindow_Height {
            get {
                return ((double)(this["MonitorWindow_Height"]));
            }
            set {
                this["MonitorWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MonitorWindow_X {
            get {
                return ((double)(this["MonitorWindow_X"]));
            }
            set {
                this["MonitorWindow_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MonitorWindow_Y {
            get {
                return ((double)(this["MonitorWindow_Y"]));
            }
            set {
                this["MonitorWindow_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Test_TT_FreshAir {
            get {
                return ((double)(this["Test_TT_FreshAir"]));
            }
            set {
                this["Test_TT_FreshAir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Test_TT_OdorPreparationDuration {
            get {
                return ((int)(this["Test_TT_OdorPreparationDuration"]));
            }
            set {
                this["Test_TT_OdorPreparationDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Test_TT_PenSniffingDuration {
            get {
                return ((double)(this["Test_TT_PenSniffingDuration"]));
            }
            set {
                this["Test_TT_PenSniffingDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Test_TT_PIDReadingInterval {
            get {
                return ((int)(this["Test_TT_PIDReadingInterval"]));
            }
            set {
                this["Test_TT_PIDReadingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2 4 6")]
        public string Test_TT_PPMs {
            get {
                return ((string)(this["Test_TT_PPMs"]));
            }
            set {
                this["Test_TT_PPMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Test_TT_RecognitionInRow {
            get {
                return ((int)(this["Test_TT_RecognitionInRow"]));
            }
            set {
                this["Test_TT_RecognitionInRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Test_TT_TurningPoints {
            get {
                return ((int)(this["Test_TT_TurningPoints"]));
            }
            set {
                this["Test_TT_TurningPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Test_TT_TurningPointsToCount {
            get {
                return ((int)(this["Test_TT_TurningPointsToCount"]));
            }
            set {
                this["Test_TT_TurningPointsToCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Test_TT_FamiliarizationDuration {
            get {
                return ((double)(this["Test_TT_FamiliarizationDuration"]));
            }
            set {
                this["Test_TT_FamiliarizationDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Test_TT_UseFeedbackLoopToReachLevel {
            get {
                return ((bool)(this["Test_TT_UseFeedbackLoopToReachLevel"]));
            }
            set {
                this["Test_TT_UseFeedbackLoopToReachLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Test_TT_UseFeedbackLoopToKeepLevel {
            get {
                return ((bool)(this["Test_TT_UseFeedbackLoopToKeepLevel"]));
            }
            set {
                this["Test_TT_UseFeedbackLoopToKeepLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Test_OP_UseFeedbackLoopToReachLevel {
            get {
                return ((bool)(this["Test_OP_UseFeedbackLoopToReachLevel"]));
            }
            set {
                this["Test_OP_UseFeedbackLoopToReachLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Test_OP_UseFeedbackLoopToKeepLevel {
            get {
                return ((bool)(this["Test_OP_UseFeedbackLoopToKeepLevel"]));
            }
            set {
                this["Test_OP_UseFeedbackLoopToKeepLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Test_TT_FlowStart {
            get {
                return ((int)(this["Test_TT_FlowStart"]));
            }
            set {
                this["Test_TT_FlowStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Test_TT_Type {
            get {
                return ((int)(this["Test_TT_Type"]));
            }
            set {
                this["Test_TT_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Test_OP_UseValveTimer {
            get {
                return ((bool)(this["Test_OP_UseValveTimer"]));
            }
            set {
                this["Test_OP_UseValveTimer"] = value;
            }
        }
    }
}
